---
- name: "Restart NGINX"
  service:
    name: nginx
    state: restarted
  when: nginx_config_test.rc != 0

- name: "Restart PHP-FPM"
  service:
    name: "php{{ php_default_version_debian }}-fpm"
    state: restarted